version: "3.9"

services:
  redis:
    image: redis
    restart: always
  web-app:
    restart: always
    build:
      context: .
    volumes:
      - ./homeland:/homeland
    ports:
      - "8000:8000"
    command: ["python","manage.py","runserver","0.0.0.0:8000"]

  worker:
    restart: always
    build:
      context: .
    volumes:
      - ./homeland:/homeland
    command: ["celery", "-A", "homeland", "worker","-l", "INFO"]

  celery-beats:
    restart: always
    build:
      context: .
    volumes:
      - ./homeland:/homeland
    command: [ "celery", "-A", "homeland", "beat","-l", "INFO","--scheduler","django_celery_beat.schedulers:DatabaseScheduler" ]

  flower:
    restart: always
    build:
      context: .
    volumes:
      - ./homeland:/homeland
    ports:
      - "5555:5555"
    command: ["celery","-A", "homeland", "flower"]
