# Generated by Django 4.2.1 on 2023-11-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='internal_currency',
            new_name='money',
        ),
    ]
