# Generated by Django 4.2.1 on 2023-11-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_apartament_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartament',
            name='img',
            field=models.ImageField(default=None, upload_to='apartament_img'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='img',
            field=models.ImageField(default=None, upload_to='hotel_img'),
        ),
    ]
