# Generated by Django 4.2.1 on 2023-11-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_profile_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='full',
        ),
    ]
