# Generated by Django 4.2.1 on 2023-11-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_internal_currency_user_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
