# Generated by Django 4.2.1 on 2023-11-29 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_hotel_full'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='order',
        ),
    ]
