# Generated by Django 4.2.1 on 2023-11-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_apartament_img_hotel_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartament',
            name='img',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='img',
        ),
    ]
