# Generated by Django 4.2.1 on 2023-11-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_apartament_img_remove_hotel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartament',
            name='img',
            field=models.ImageField(default='1.jpg', upload_to='apartament_img'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='img',
            field=models.ImageField(default='1.jpg', upload_to='hotel_img'),
        ),
    ]
