# Generated by Django 4.2.1 on 2023-11-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='leave_date',
            field=models.DateField(default='2023-11-28'),
        ),
    ]
