# Generated by Django 4.2.1 on 2023-11-28 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_leave_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arrive_date',
            field=models.DateField(default=datetime.date(2023, 11, 28)),
        ),
        migrations.AlterField(
            model_name='order',
            name='leave_date',
            field=models.DateField(default=datetime.date(2023, 11, 28)),
        ),
    ]
